[build]
# target = "./client/index.html"
dist = "./dist"

# [watch]
# watch = ["./src", "./client", "./Cargo.toml"]
# ignore = ["./dist", "./target"]

# [serve]
# address = "127.0.0.1"
# port = 8080
# open = false
# proxy_backend = "http://127.0.0.1:8000"

# [[proxy]]
# rewrite = "/api"
# backend = "http://127.0.0.1:8000"